project:
  type: website
  output-dir: docs
  render:
    - index.qmd
           
website:
  title: ""
  search: false  
  navbar:
    search: false
    title: BUSI 520
    right:

      - text: Github Repo
        href: https://github.com/kerryback/BUSI-520-notebooks
        
format: 
  html:
    theme: cosmo
    scss: styles.css
    
   



