project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - assignments.qmd
    - assignments1.qmd
           
website:
  title: ""
  search: false  
  navbar:
    search: false
    title: BUSI 520
    right:

      - text: Github Repo (under development)
        href: https://github.com/kerryback/BUSI-520-notebooks
      - text: Assignments
        file: assignments.qmd
      - text: Home
        file: index.qmd
        
format: 
  html:
    theme: cosmo
    scss: styles.css
    
   



