project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - slides.qmd
    - solutions.qmd
    - assignments.qmd
    - assignment1.qmd
    - assignment2.qmd
           
website:
  title: ""
  search: false  
  navbar:
    search: false
    title: BUSI 520
    file: index.qmd
    right:
      
      - text: Slides
        file: slides.qmd
      - text: Assignments
        file: assignments.qmd
      - text: Solutions
        file: solutions.qmd
      - text: Notebooks
        href: https://github.com/kerryback/BUSI-520-notebooks
      
        
format: 
  html:
    theme: cosmo
    scss: styles.css
    
   



